version: 2

models:
  - name: stg_telegram_messages
    description: Cleaned Telegram messages from the raw layer
    columns:
      - name: message_id
        description: Unique ID of the message
        tests: [not_null, unique]

      - name: channel_name
        description: Telegram channel this message came from
        tests: [not_null]

      - name: message_text
        description: Message content

      - name: message_date
        description: Timestamp of when the message was posted
        tests: [not_null]

      - name: has_media
        description: Boolean indicating if the message has media
